[package]
name = "txtencrypt"
version = "0.1.0"
authors = ["Matthew Ashton-Knochel <matthewashtonknochel@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aes-gcm = "0.3.0"

aead = "0.2.0"

rand = "0.7.2"
